export const SN_PICKLIST = 'picklist'
export const PICKLIST_CURRENT = SN_PICKLIST + '/CURRENT'
export const PICKLIST_ITEMS = SN_PICKLIST + '/ITEMS'
export const PICKLIST_SELECTED_PRODUCTS_UPDATED = SN_PICKLIST + '/SELECTED_PRODUCTS_UPDATED'
