export const SN_PICKLIST = 'picklist'
export const PICKLISTS_UPDATED = SN_PICKLIST + '/UPDATED'
export const PICKLIST_CURRENT_UPDATED = SN_PICKLIST + '/CURRENT_UPDATED'
export const PICKLIST_CMPLTD_UPDATED = SN_PICKLIST + '/CMPLTD_UPDATED'
